import 'package:flutter/material.dart';
const kPrimaryColor = Color(0xFF6F35A5);
const kPrimaryLightColor = Color(0xFFF1E6FF);

/// Generated by AssetsRefGenerator on 2020/11/02
class Res {
  /*static const String chat = "assets/icons/chat.svg";
  static const String facebook = "assets/icons/facebook.svg";
  static const String google_plus = "assets/icons/google-plus.svg";
  static const String login = "assets/icons/login.svg";
  static const String signup = "assets/icons/signup.svg";
  static const String twitter = "assets/icons/twitter.svg";
  static const String login_bottom = "assets/images/login_bottom.png";
  static const String main_bottom = "assets/images/main_bottom.png";
  static const String main_top = "assets/images/main_top.png";
  static const String signup_top = "assets/images/signup_top.png";*/
  static String tname  ;
  static String tid;
  static String tNumber; //= "+919313632001";
  static int trainer_code = 786;
 // static LoginStore loginStore;
  static const Color purlight = Color.fromRGBO(96, 0, 148, 0.25);
  //Color(0xFF600094);
  static const Color pur = Color.fromRGBO(96, 0, 148, .8);
  static const Color  start = Color(0xFFE55CE4);
  static const Color  end = Color(0xFFBB75FB);
  //static const Color pur = Colors.purple;
  static const Color purdark = Color.fromRGBO(96, 0, 148, 1);
  static final headerTextStyle = const TextStyle(
      fontFamily: 'Poppins',
      color: Colors.white,
      fontSize: 18.0,
      fontWeight: FontWeight.w600
  );
  static final regularTextStyle = const TextStyle(
      fontFamily: 'Poppins',
      color:Color(0xffb6b2df),
      // color: Colors.white,
      fontSize: 9.0,
      fontWeight: FontWeight.w400
  );
  static final subHeaderTextStyle = const TextStyle(
      fontFamily: 'Poppins',
      color: Color(0xffb6b2df),
      fontSize: 12.0,
      fontWeight: FontWeight.w400
  );

  static List room = [
    /*  {
      "rname":"Sagar",
      "rrepeat":"Mon,Tue,Wed",
      "rdescription":"asdads",
      "rtime":"20:30",
      "duration":"60",
      "rlimit":"99"
    },
    {
      "rname":"Sagar",
      "rrepeat":"Mon,Tue,Wed",
      "rdescription":"asdads",
      "rtime":"20:30",
      "duration":"60",
      "rlimit":"99"
    },
    {
      "rname":"Sagar",
      "rrepeat":"Mon,Tue,Wed",
      "rdescription":"asdads",
      "rtime":"20:30",
      "duration":"60",
      "rlimit":"99"
    },
    {
      "rname":"Sagar",
      "rrepeat":"Mon,Tue,Wed",
      "rdescription":"asdads",
      "rtime":"20:30",
      "duration":"60",
      "rlimit":"99"
    },*/
  ];
}
